// packages/solid/src/components/Filmstrip.tsx
import { For, Show, createMemo } from 'solid-js';
import type { Component } from 'solid-js';
import { useAnnotator } from '../state/annotator-context.js';
import type { ImageId, ImageSource } from '@osdlabel/viewer-api';
import {
  getCellAssignmentState,
  CELL_ASSIGNMENT_BORDER_COLOR,
  CELL_ASSIGNMENT_PLACEHOLDER_BACKGROUND,
  CELL_ASSIGNMENT_TITLE,
  CELL_ASSIGNMENT_CLEAR_LABEL,
  type CellAssignmentState,
} from 'osdlabel';

export interface FilmstripProps {
  readonly images: readonly ImageSource[];
  readonly position: 'left' | 'right' | 'bottom';
}

const Filmstrip: Component<FilmstripProps> = (props) => {
  const { uiState, actions } = useAnnotator();

  const assignmentState = (imageId: ImageId): CellAssignmentState =>
    getCellAssignmentState(uiState, imageId);

  // A thumbnail click only ever assigns, so it is idempotent: clicking the
  // image the active cell already shows re-assigns it, exactly as before this
  // control existed. Clearing is the separate badge below, because a
  // double-click on a thumbnail would otherwise assign then immediately clear,
  // and a clear drops the cell's view transform with no undo.
  //
  // Both gestures name `activeCellIndex` directly, which the reducer keeps
  // inside the grid — that invariant is what makes deriving a target cell here
  // unnecessary.
  const assign = (image: ImageSource) => {
    actions.assignImageToCell(uiState.activeCellIndex, image.id);
  };

  const clearActiveCell = (event: MouseEvent) => {
    // Without this the wrapper's handler also fires and re-assigns the image
    // the badge just removed.
    event.stopPropagation();
    actions.unassignImageFromCell(uiState.activeCellIndex);
  };

  const isVertical = () => props.position === 'left' || props.position === 'right';

  return (
    <div
      data-testid="filmstrip"
      style={{
        display: 'flex',
        'flex-direction': isVertical() ? 'column' : 'row',
        'overflow-y': isVertical() ? 'auto' : 'hidden',
        'overflow-x': isVertical() ? 'hidden' : 'auto',
        background: '#1a1a2e',
        padding: '4px',
        gap: '4px',
        [isVertical() ? 'width' : 'height']: '120px',
        'flex-shrink': '0',
      }}
    >
      <For each={[...props.images]}>
        {(image) => {
          const state = createMemo(() => assignmentState(image.id));

          return (
            <div
              data-testid={`filmstrip-item-${image.id}`}
              data-assignment={state()}
              title={CELL_ASSIGNMENT_TITLE[state()]}
              onClick={() => assign(image)}
              style={{
                [isVertical() ? 'width' : 'height']: '100%',
                [isVertical() ? 'height' : 'width']: '80px',
                'flex-shrink': '0',
                border: `2px solid ${CELL_ASSIGNMENT_BORDER_COLOR[state()]}`,
                'border-radius': '4px',
                overflow: 'hidden',
                cursor: 'pointer',
                position: 'relative',
                'box-sizing': 'border-box',
              }}
            >
              {image.thumbnailUrl ? (
                <img
                  src={image.thumbnailUrl}
                  alt={image.label ?? image.id}
                  style={{
                    width: '100%',
                    height: '100%',
                    'object-fit': 'cover',
                  }}
                />
              ) : (
                <div
                  style={{
                    width: '100%',
                    height: '100%',
                    display: 'flex',
                    'align-items': 'center',
                    'justify-content': 'center',
                    background: CELL_ASSIGNMENT_PLACEHOLDER_BACKGROUND[state()],
                    color: '#aaa',
                    'font-size': '10px',
                    'font-family': 'system-ui, sans-serif',
                    'text-align': 'center',
                    padding: '4px',
                    'box-sizing': 'border-box',
                  }}
                >
                  {image.label ?? image.id}
                </div>
              )}
              {/* The only control that empties a cell. A real button, so it is
                  reachable by keyboard and named for assistive tech — which is
                  also the one gesture in this component that loses work. */}
              <Show when={state() === 'active'}>
                <button
                  type="button"
                  data-testid={`filmstrip-clear-${image.id}`}
                  aria-label={CELL_ASSIGNMENT_CLEAR_LABEL}
                  title={CELL_ASSIGNMENT_CLEAR_LABEL}
                  onClick={clearActiveCell}
                  style={{
                    position: 'absolute',
                    top: '2px',
                    right: '2px',
                    width: '16px',
                    height: '16px',
                    padding: '0',
                    display: 'flex',
                    'align-items': 'center',
                    'justify-content': 'center',
                    'border-radius': '50%',
                    border: 'none',
                    background: 'rgba(0, 0, 0, 0.65)',
                    color: '#fff',
                    'font-size': '11px',
                    'line-height': '1',
                    'font-family': 'system-ui, sans-serif',
                    cursor: 'pointer',
                  }}
                >
                  ✕
                </button>
              </Show>
            </div>
          );
        }}
      </For>
    </div>
  );
};

export default Filmstrip;

// packages/react/src/components/Filmstrip.tsx
import type { MouseEvent } from 'react';
import { useAnnotator } from '../state/annotator-context.js';
import type { ImageId, ImageSource } from '@osdlabel/viewer-api';
import {
  getCellAssignmentState,
  CELL_ASSIGNMENT_BORDER_COLOR,
  CELL_ASSIGNMENT_PLACEHOLDER_BACKGROUND,
  CELL_ASSIGNMENT_TITLE,
  CELL_ASSIGNMENT_CLEAR_LABEL,
  type CellAssignmentState,
} from 'osdlabel';

export interface FilmstripProps {
  readonly images: readonly ImageSource[];
  readonly position: 'left' | 'right' | 'bottom';
}

export default function Filmstrip({ images, position }: FilmstripProps) {
  const { uiState, actions } = useAnnotator();

  const assignmentState = (imageId: ImageId): CellAssignmentState =>
    getCellAssignmentState(uiState, imageId);

  // A thumbnail click only ever assigns, so it is idempotent: clicking the
  // image the active cell already shows re-assigns it, exactly as before this
  // control existed. Clearing is the separate badge below, because a
  // double-click on a thumbnail would otherwise assign then immediately clear,
  // and a clear drops the cell's view transform with no undo.
  //
  // Both gestures name `activeCellIndex` directly, which the reducer keeps
  // inside the grid — that invariant is what makes deriving a target cell here
  // unnecessary.
  const assign = (image: ImageSource) => {
    actions.assignImageToCell(uiState.activeCellIndex, image.id);
  };

  const clearActiveCell = (event: MouseEvent<HTMLButtonElement>) => {
    // Without this the wrapper's handler also fires and re-assigns the image
    // the badge just removed.
    event.stopPropagation();
    actions.unassignImageFromCell(uiState.activeCellIndex);
  };

  const isVertical = position === 'left' || position === 'right';

  return (
    <div
      data-testid="filmstrip"
      style={{
        display: 'flex',
        flexDirection: isVertical ? 'column' : 'row',
        overflowY: isVertical ? 'auto' : 'hidden',
        overflowX: isVertical ? 'hidden' : 'auto',
        background: '#1a1a2e',
        padding: '4px',
        gap: '4px',
        [isVertical ? 'width' : 'height']: '120px',
        flexShrink: 0,
      }}
    >
      {[...images].map((image) => {
        const state = assignmentState(image.id);

        return (
          <div
            key={image.id}
            data-testid={`filmstrip-item-${image.id}`}
            data-assignment={state}
            title={CELL_ASSIGNMENT_TITLE[state]}
            onClick={() => assign(image)}
            style={{
              [isVertical ? 'width' : 'height']: '100%',
              [isVertical ? 'height' : 'width']: '80px',
              flexShrink: 0,
              border: `2px solid ${CELL_ASSIGNMENT_BORDER_COLOR[state]}`,
              borderRadius: '4px',
              overflow: 'hidden',
              cursor: 'pointer',
              position: 'relative',
              boxSizing: 'border-box',
            }}
          >
            {image.thumbnailUrl ? (
              <img
                src={image.thumbnailUrl}
                alt={image.label ?? image.id}
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                }}
              />
            ) : (
              <div
                style={{
                  width: '100%',
                  height: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  background: CELL_ASSIGNMENT_PLACEHOLDER_BACKGROUND[state],
                  color: '#aaa',
                  fontSize: '10px',
                  fontFamily: 'system-ui, sans-serif',
                  textAlign: 'center',
                  padding: '4px',
                  boxSizing: 'border-box',
                }}
              >
                {image.label ?? image.id}
              </div>
            )}
            {/* The only control that empties a cell. A real button, so it is
                reachable by keyboard and named for assistive tech — which is
                also the one gesture in this component that loses work. */}
            {state === 'active' && (
              <button
                type="button"
                data-testid={`filmstrip-clear-${image.id}`}
                aria-label={CELL_ASSIGNMENT_CLEAR_LABEL}
                title={CELL_ASSIGNMENT_CLEAR_LABEL}
                onClick={clearActiveCell}
                style={{
                  position: 'absolute',
                  top: '2px',
                  right: '2px',
                  width: '16px',
                  height: '16px',
                  padding: 0,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  borderRadius: '50%',
                  border: 'none',
                  background: 'rgba(0, 0, 0, 0.65)',
                  color: '#fff',
                  fontSize: '11px',
                  lineHeight: '1',
                  fontFamily: 'system-ui, sans-serif',
                  cursor: 'pointer',
                }}
              >
                ✕
              </button>
            )}
          </div>
        );
      })}
    </div>
  );
}
