// packages/solid/src/hooks/useAnnotationTool.ts
import { createEffect, onCleanup } from 'solid-js';
import type { FabricObject } from 'fabric';
import type { FabricOverlay } from '@osdlabel/fabric-osd';
import type { AnnotationTool, AddAnnotationParams } from '@osdlabel/fabric-annotations';
import type { AnnotationId, Point, ToolType } from '@osdlabel/annotation';
import type { ImageId } from '@osdlabel/viewer-api';
import { DEFAULT_CELL_TRANSFORM } from '@osdlabel/viewer-api';
import {
  createAnnotationTool,
  createDragVectorControl,
  getScenePointFromEvent,
  getToneValue,
  processToolAddAnnotation,
  processToolUpdateAnnotation,
  processObjectModified,
  VIEWER_CONTROL_SPECS,
} from 'osdlabel';
import type { DragAxisBehavior, ViewerControlAxisSpec } from 'osdlabel';
import type { ToolCallbacks } from '@osdlabel/fabric-annotations';
import { useAnnotator } from '../state/annotator-context.js';

interface FabricPointerEvent {
  readonly e: MouseEvent | PointerEvent | TouchEvent;
  readonly scenePoint?: { readonly x: number; readonly y: number };
  readonly absolutePointer?: { readonly x: number; readonly y: number };
  readonly target?: FabricObject | null;
}

export function useAnnotationTool(
  overlay: () => FabricOverlay | undefined,
  imageId: () => ImageId | undefined,
  isActive: () => boolean,
) {
  const {
    uiState,
    contextState,
    annotationState,
    constraintStatus,
    actions,
    activeToolKeyHandlerRef,
    shortcuts,
    vertexEditConfig,
    vertexMarkerOptions,
  } = useAnnotator();

  // Auto-switch to select tool when active drawing tool becomes disabled (limit reached)
  createEffect(() => {
    const tool = uiState.activeTool;
    if (tool && tool !== 'select') {
      const status = constraintStatus();
      if (!status[tool as ToolType].enabled) {
        actions.setActiveTool('select');
      }
    }
  });

  // Handle object modification (resize, rotate, move) globally
  createEffect(() => {
    const ov = overlay();
    const imgId = imageId();

    if (!ov || !imgId) return;

    const handleObjectModified = (e: { target: FabricObject }) => {
      const result = processObjectModified(e.target, annotationState, imgId);
      if (result) {
        actions.updateAnnotation(result.id, imgId, {
          geometry: result.geometry!,
          rawAnnotationData: result.rawAnnotationData,
        });
      }
    };

    ov.canvas.on('object:modified', handleObjectModified);
    onCleanup(() => {
      ov.canvas.off('object:modified', handleObjectModified);
    });
  });

  createEffect(() => {
    const ov = overlay();
    const active = isActive();
    const viewerControl = uiState.activeViewerControl;
    const type = uiState.activeTool;
    const imgId = imageId();

    if (!ov || !imgId) {
      return;
    }

    // A drag-driven viewer control takes precedence over annotation tools:
    // the overlay enters customControl mode and forwards pointer events to the
    // control's handler. This is the single authority over setMode, so there is
    // no second effect that could race it. Drag parameters come from the shared
    // VIEWER_CONTROL_SPECS registry so Solid and React behave identically.
    const spec = viewerControl ? VIEWER_CONTROL_SPECS[viewerControl] : undefined;
    if (active && viewerControl && spec) {
      const axis = (axisSpec: ViewerControlAxisSpec): DragAxisBehavior => ({
        getValue: () =>
          getToneValue(
            uiState.cellTransforms[uiState.activeCellIndex] ?? DEFAULT_CELL_TRANSFORM,
            axisSpec.field,
          ),
        setValue: (value) =>
          axisSpec.field === 'exposure'
            ? actions.setActiveImageExposure(value)
            : actions.setActiveImageContrast(value),
        invert: axisSpec.invert,
        sensitivity: axisSpec.sensitivity,
        step: axisSpec.step,
        min: axisSpec.min,
        max: axisSpec.max,
      });
      ov.setCustomControlHandler(
        createDragVectorControl({
          ...(spec.x ? { x: axis(spec.x) } : {}),
          ...(spec.y ? { y: axis(spec.y) } : {}),
        }),
      );
      ov.setMode('customControl');
      onCleanup(() => {
        ov.setCustomControlHandler(null);
      });
      return;
    }

    if (!active || !type) {
      ov.setMode('navigation');
      return;
    }

    const tool: AnnotationTool | null = createAnnotationTool(type, {
      vertexEdit: vertexEditConfig,
      vertexMarkers: vertexMarkerOptions,
    });

    if (!tool) {
      ov.setMode('navigation');
      return;
    }

    // Construct callbacks from context
    const callbacks: ToolCallbacks = {
      getActiveContextId: () => contextState.activeContextId,
      getToolConstraint: (toolType) => {
        const activeContextId = contextState.activeContextId;
        if (!activeContextId) return undefined;
        const activeContext = contextState.contexts.find((c) => c.id === activeContextId);
        return activeContext?.tools.find((t) => t.type === toolType);
      },
      canAddAnnotation: (toolType: ToolType) => {
        const status = constraintStatus();
        return status[toolType].enabled;
      },
      addAnnotation: (params: AddAnnotationParams) => {
        const processed = processToolAddAnnotation(params);
        if (!processed) return;
        actions.addAnnotation(processed);
      },
      updateAnnotation: (id: AnnotationId, imageIdArg: ImageId, fabricObject: FabricObject) => {
        const patch = processToolUpdateAnnotation(id, imageIdArg, fabricObject, annotationState);
        if (!patch) return;
        actions.updateAnnotation(id, imageIdArg, patch);
      },
      deleteAnnotation: (id, imageIdArg) => actions.deleteAnnotation(id, imageIdArg),
      setSelectedAnnotation: (id) => actions.setSelectedAnnotation(id),
      getAnnotation: (id, imageIdArg) => {
        const imageAnns = annotationState.byImage[imageIdArg];
        return imageAnns?.[id];
      },
    };

    // Activate tool
    ov.setMode('annotation');
    tool.activate(ov, imgId, callbacks, shortcuts);

    const keyHandler = (e: KeyboardEvent) => tool!.onKeyDown(e);
    activeToolKeyHandlerRef.handler = keyHandler;

    const isDrawingTool = type !== 'select';

    // Track whether we suppressed mouse:down so we also suppress mouse:up
    let suppressedDown = false;

    // Handlers
    const handleDown = (opt: FabricPointerEvent) => {
      if (!tool) return;

      // For drawing tools, skip if the click landed on an existing annotation object.
      if (isDrawingTool && opt.target) {
        if (opt.target.id) {
          suppressedDown = true;
          return;
        }
      }

      suppressedDown = false;
      const p = getScenePointFromEvent((pt: Point) => ov.screenToImage(pt), opt);
      tool.onPointerDown(opt.e as PointerEvent, p);
    };

    const handleMove = (opt: FabricPointerEvent) => {
      if (!tool || suppressedDown) return;
      const p = getScenePointFromEvent((pt: Point) => ov.screenToImage(pt), opt);
      tool.onPointerMove(opt.e as PointerEvent, p);
    };

    const handleUp = (opt: FabricPointerEvent) => {
      if (!tool || suppressedDown) {
        suppressedDown = false;
        return;
      }
      const p = getScenePointFromEvent((pt: Point) => ov.screenToImage(pt), opt);
      tool.onPointerUp(opt.e as PointerEvent, p);
    };

    // Double clicks do not come through Fabric: input is routed by an OSD
    // MouseTracker, so `detail` is 0 on every forwarded pointerdown and the
    // browser's own dblclick never reaches Fabric's canvas (issue #168).
    // Unconditional: a suppressed press adds no vertex, and the tool decides
    // for itself whether the gesture contributed one.
    const unsubscribeDoubleClick = ov.onDoubleClick((e, p) => {
      tool.onDoubleClick?.(e, p);
    });

    ov.canvas.on('mouse:down', handleDown);
    ov.canvas.on('mouse:move', handleMove);
    ov.canvas.on('mouse:up', handleUp);

    onCleanup(() => {
      if (activeToolKeyHandlerRef.handler === keyHandler) {
        activeToolKeyHandlerRef.handler = null;
      }
      unsubscribeDoubleClick();
      ov.canvas.off('mouse:down', handleDown);
      ov.canvas.off('mouse:move', handleMove);
      ov.canvas.off('mouse:up', handleUp);
      if (tool) {
        tool.deactivate();
      }
    });
  });
}

// packages/react/src/hooks/useAnnotationTool.ts
import { useEffect, useRef } from 'react';
import type { FabricObject } from 'fabric';
import type { FabricOverlay } from '@osdlabel/fabric-osd';
import type { AnnotationTool, AddAnnotationParams } from '@osdlabel/fabric-annotations';
import type { AnnotationId, Point, ToolType } from '@osdlabel/annotation';
import type { ImageId } from '@osdlabel/viewer-api';
import { DEFAULT_CELL_TRANSFORM } from '@osdlabel/viewer-api';
import {
  createAnnotationTool,
  createDragVectorControl,
  getScenePointFromEvent,
  getToneValue,
  processToolAddAnnotation,
  processToolUpdateAnnotation,
  processObjectModified,
  VIEWER_CONTROL_SPECS,
} from 'osdlabel';
import type { DragAxisBehavior, ViewerControlAxisSpec } from 'osdlabel';
import type { ToolCallbacks } from '@osdlabel/fabric-annotations';
import { useAnnotator } from '../state/annotator-context.js';

interface FabricPointerEvent {
  readonly e: MouseEvent | PointerEvent | TouchEvent;
  readonly scenePoint?: { readonly x: number; readonly y: number };
  readonly absolutePointer?: { readonly x: number; readonly y: number };
  readonly target?: FabricObject | null;
}

export function useAnnotationTool(
  overlay: FabricOverlay | undefined,
  imageId: ImageId | undefined,
  isActive: boolean,
) {
  const {
    uiState,
    contextState,
    annotationState,
    constraintStatus,
    actions,
    activeToolKeyHandlerRef,
    shortcuts,
    vertexEditConfig,
    vertexMarkerOptions,
  } = useAnnotator();

  // Auto-switch to select tool when active drawing tool becomes disabled
  useEffect(() => {
    const tool = uiState.activeTool;
    if (tool && tool !== 'select') {
      if (!constraintStatus[tool as ToolType].enabled) {
        actions.setActiveTool('select');
      }
    }
  }, [uiState.activeTool, constraintStatus, actions]);

  // Use refs for values needed in event handlers to avoid stale closures
  const annotationStateRef = useRef(annotationState);
  annotationStateRef.current = annotationState;
  const contextStateRef = useRef(contextState);
  contextStateRef.current = contextState;
  const constraintStatusRef = useRef(constraintStatus);
  constraintStatusRef.current = constraintStatus;
  const uiStateRef = useRef(uiState);
  uiStateRef.current = uiState;

  // Handle object:modified events
  useEffect(() => {
    if (!overlay || !imageId) return;

    const handleObjectModified = (e: { target: FabricObject }) => {
      const result = processObjectModified(e.target, annotationStateRef.current, imageId);
      if (result) {
        actions.updateAnnotation(result.id, imageId, {
          geometry: result.geometry!,
          rawAnnotationData: result.rawAnnotationData,
        });
      }
    };

    overlay.canvas.on('object:modified', handleObjectModified);
    return () => {
      overlay.canvas.off('object:modified', handleObjectModified);
    };
  }, [overlay, imageId, actions]);

  // Main tool lifecycle effect
  useEffect(() => {
    if (!overlay || !imageId) return;

    // A drag-driven viewer control takes precedence over annotation tools: the
    // overlay enters customControl mode and forwards pointer events to the
    // control's handler. This effect is the single authority over setMode, so
    // no second effect can race it. getValue reads through a ref to avoid a
    // stale closure across renders. Drag parameters come from the shared
    // VIEWER_CONTROL_SPECS registry so React and Solid behave identically.
    const viewerControl = uiState.activeViewerControl;
    const spec = viewerControl ? VIEWER_CONTROL_SPECS[viewerControl] : undefined;
    if (isActive && viewerControl && spec) {
      const axis = (axisSpec: ViewerControlAxisSpec): DragAxisBehavior => ({
        getValue: () =>
          getToneValue(
            uiStateRef.current.cellTransforms[uiStateRef.current.activeCellIndex] ??
              DEFAULT_CELL_TRANSFORM,
            axisSpec.field,
          ),
        setValue: (value) =>
          axisSpec.field === 'exposure'
            ? actions.setActiveImageExposure(value)
            : actions.setActiveImageContrast(value),
        invert: axisSpec.invert,
        sensitivity: axisSpec.sensitivity,
        step: axisSpec.step,
        min: axisSpec.min,
        max: axisSpec.max,
      });
      overlay.setCustomControlHandler(
        createDragVectorControl({
          ...(spec.x ? { x: axis(spec.x) } : {}),
          ...(spec.y ? { y: axis(spec.y) } : {}),
        }),
      );
      overlay.setMode('customControl');
      return () => {
        overlay.setCustomControlHandler(null);
      };
    }

    if (!isActive || !uiState.activeTool) {
      overlay.setMode('navigation');
      return;
    }

    const tool: AnnotationTool | null = createAnnotationTool(uiState.activeTool, {
      vertexEdit: vertexEditConfig,
      vertexMarkers: vertexMarkerOptions,
    });

    if (!tool) {
      overlay.setMode('navigation');
      return;
    }

    const callbacks: ToolCallbacks = {
      getActiveContextId: () => contextStateRef.current.activeContextId,
      getToolConstraint: (toolType) => {
        const cs = contextStateRef.current;
        const activeContextId = cs.activeContextId;
        if (!activeContextId) return undefined;
        const activeContext = cs.contexts.find((c) => c.id === activeContextId);
        return activeContext?.tools.find((t) => t.type === toolType);
      },
      canAddAnnotation: (toolType: ToolType) => {
        return constraintStatusRef.current[toolType].enabled;
      },
      addAnnotation: (params: AddAnnotationParams) => {
        const processed = processToolAddAnnotation(params);
        if (!processed) return;
        actions.addAnnotation(processed);
      },
      updateAnnotation: (id: AnnotationId, imageIdArg: ImageId, fabricObject: FabricObject) => {
        const patch = processToolUpdateAnnotation(
          id,
          imageIdArg,
          fabricObject,
          annotationStateRef.current,
        );
        if (!patch) return;
        actions.updateAnnotation(id, imageIdArg, patch);
      },
      deleteAnnotation: (id, imageIdArg) => actions.deleteAnnotation(id, imageIdArg),
      setSelectedAnnotation: (id) => actions.setSelectedAnnotation(id),
      getAnnotation: (id, imageIdArg) => {
        const imageAnns = annotationStateRef.current.byImage[imageIdArg];
        return imageAnns?.[id];
      },
    };

    overlay.setMode('annotation');
    tool.activate(overlay, imageId, callbacks, shortcuts);

    const keyHandler = (e: KeyboardEvent) => tool.onKeyDown(e);
    activeToolKeyHandlerRef.handler = keyHandler;

    const isDrawingTool = uiState.activeTool !== 'select';
    let suppressedDown = false;

    const handleDown = (opt: FabricPointerEvent) => {
      if (isDrawingTool && opt.target?.id) {
        suppressedDown = true;
        return;
      }
      suppressedDown = false;
      const p = getScenePointFromEvent((pt: Point) => overlay.screenToImage(pt), opt);
      tool.onPointerDown(opt.e as PointerEvent, p);
    };

    const handleMove = (opt: FabricPointerEvent) => {
      if (suppressedDown) return;
      const p = getScenePointFromEvent((pt: Point) => overlay.screenToImage(pt), opt);
      tool.onPointerMove(opt.e as PointerEvent, p);
    };

    const handleUp = (opt: FabricPointerEvent) => {
      if (suppressedDown) {
        suppressedDown = false;
        return;
      }
      const p = getScenePointFromEvent((pt: Point) => overlay.screenToImage(pt), opt);
      tool.onPointerUp(opt.e as PointerEvent, p);
    };

    // Double clicks do not come through Fabric: input is routed by an OSD
    // MouseTracker, so `detail` is 0 on every forwarded pointerdown and the
    // browser's own dblclick never reaches Fabric's canvas (issue #168).
    // Unconditional: a suppressed press adds no vertex, and the tool decides
    // for itself whether the gesture contributed one.
    const unsubscribeDoubleClick = overlay.onDoubleClick((e, p) => {
      tool.onDoubleClick?.(e, p);
    });

    overlay.canvas.on('mouse:down', handleDown);
    overlay.canvas.on('mouse:move', handleMove);
    overlay.canvas.on('mouse:up', handleUp);

    return () => {
      if (activeToolKeyHandlerRef.handler === keyHandler) {
        activeToolKeyHandlerRef.handler = null;
      }
      unsubscribeDoubleClick();
      overlay.canvas.off('mouse:down', handleDown);
      overlay.canvas.off('mouse:move', handleMove);
      overlay.canvas.off('mouse:up', handleUp);
      tool.deactivate();
    };
  }, [
    overlay,
    imageId,
    isActive,
    uiState.activeTool,
    uiState.activeViewerControl,
    shortcuts,
    vertexEditConfig,
    vertexMarkerOptions,
    actions,
    activeToolKeyHandlerRef,
  ]);
}
